# Generated by Django 6.0.1 on 2026-03-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
    ]
