# Generated by Django 6.0.1 on 2026-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_employee_email_remove_employee_mothers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(),
        ),
    ]
