# Generated by Django 6.0.1 on 2026-03-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_employee_join_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
